import fs from 'node:fs/promises';

const destination = new URL('../encontro-1/index.html', import.meta.url);
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const slide = (topic, title, body, note, classes = '') => `<section class="${classes}" data-topic="${topic}" data-title="${esc(title)}" data-note="${esc(note)}">${body}</section>`;
const tag = text => `<span class="kicker">${text}</span>`;
const prompt = (question, answer = '') => `<div class="dialogue"><p class="dialogue-question">${question}</p>${answer ? `<div class="dialogue-answer">${answer}</div>` : ''}</div>`;
const example = (label, text) => `<div class="worked-example"><span>${label}</span><p>${text}</p></div>`;
const cards = items => `<div class="grid" style="--cols:${Math.min(items.length, 4)}">${items.map(([head, text, kind = '']) => `<div class="card ${kind}"><b>${head}</b><p>${text}</p></div>`).join('')}</div>`;
const steps = items => `<div class="flow">${items.map(([head, text], index) => `<div class="step${index === items.length - 1 ? ' hot' : ''}"><span>${head}</span>${text}</div>`).join('')}</div>`;
const compare = rows => `<div class="conversation-table">${rows.map(([a,b,c]) => `<div><strong>${a}</strong><p>${b}</p><em>${c}</em></div>`).join('')}</div>`;

const slides = [];

slides.push(`<section class="cover" data-topic="0" data-title="Capa" data-note="Acolha o participante. Explique que este material foi reconstruído para permitir estudo, retomada e aplicação após o encontro."><div class="cover-grid"><div>${tag('TJRS · Centro de Formação e Desenvolvimento de Pessoas')}<h1>FOFO TECH<span>Dia 1 em diálogo</span></h1><p class="lead">Mentimeter e Gemini Notebook: da escuta do grupo à produção responsável com fontes.</p><span class="pill">Material de estudo e retomada</span></div><div class="logo-stage"><img src="../assets/logo-cjud.jpg" alt="Logo do CJUD"></div></div></section>`);

slides.push(slide(0,'Fernando de Assis Alves',`<div class="split"><div class="bio">${tag('Quem conversa com você')}<h2>Fernando de Assis Alves</h2><p>Pedagogo, mestre em Educação e Comunicação pela UnB e doutorando em Educação. Atua na administração pública como professor e formador.</p><p>Sua trajetória conecta educação, comunicação, tecnologias, inovação e desenvolvimento de competências complexas.</p><div class="tags"><span class="tag">Educação</span><span class="tag">Tecnologias</span><span class="tag">Gestão pública</span></div></div><div class="portrait"><img src="../assets/instrutor-fernando.jpg" alt="Fernando de Assis Alves"></div></div>`,`Apresente Fernando pela relação entre educação, comunicação e tecnologia. Não leia o currículo; conecte a trajetória às escolhas pedagógicas do encontro.`));

slides.push(slide(0,'Ânderson Porto',`<div class="split"><div class="bio">${tag('Quem conversa com você')}<h2>Ânderson Porto</h2><p>Facilitador e instrutor em programas formativos para o Poder Judiciário. Mestrando em Gestão Pública pela UnB e especialista em Inovação em Tecnologias Educacionais.</p><p>Atua com educação corporativa, desenho instrucional, liderança, negociação e inovação, sempre buscando transformar conceitos em decisões aplicáveis.</p><div class="tags"><span class="tag">Educação corporativa</span><span class="tag">Desenho instrucional</span><span class="tag">Facilitação</span></div></div><div class="portrait"><img src="../assets/instrutor-anderson.png" alt="Ânderson Porto"></div></div>`,`Apresente Ânderson pela perspectiva aplicada: conceitos precisam se transformar em escolhas possíveis de desenho, mediação e avaliação.`));

slides.push(slide(0,'Como usar este material',`${tag('Um convite antes de começar')}<h2>Você não precisa apenas “passar pelos slides”.</h2>${prompt('Use este material como uma conversa que continua depois do curso.',`<p>Leia as perguntas, tente responder antes de avançar, confronte os exemplos com sua prática e registre o que você mudaria em uma formação real.</p>`)}${cards([['Pare','Dê tempo para formular uma resposta própria.'],['Compare','Observe onde sua hipótese se aproxima ou se afasta do exemplo.'],['Aplique','Traduza a ideia para um problema real do trabalho.'],['Revise','Volte à decisão inicial e melhore-a.']])}`,`Explique o novo contrato de leitura. Este deck é material instrucional: cada pergunta deve produzir pensamento antes da explicação.`));

slides.push(slide(0,'Nosso pacto de aprendizagem',`${tag('Como aprendemos juntos')}<h2>Experimentar é importante. Pensar sobre a experiência é indispensável.</h2>${compare([['Quando algo funciona','Perguntamos que ação de aprendizagem foi ampliada.','Não confundimos fluidez técnica com aprendizagem.'],['Quando algo falha','Investigamos o que a falha revela sobre o desenho.','Não transformamos erro técnico em constrangimento.'],['Quando a IA responde','Voltamos às fontes e assumimos a revisão.','Não terceirizamos julgamento nem autoria.']])}`,`Combine prática, ajuda entre pares, cuidado com dados e direito de errar. Reforce que o curso não é competição de domínio tecnológico.`));

slides.push(slide(1,'Momento de se apresentar',`<div class="intro-copy">${tag('Antes das ferramentas, as pessoas')}<h2>Quem está construindo esta conversa?</h2><p class="intro-command">Entre no grupo e apresente-se usando o formato que melhor comunica algo importante sobre você.</p><p class="intro-action">Texto, imagem, áudio ou vídeo são possibilidades. A escolha também comunica.</p><div class="activity-meta"><span>5 a 8 minutos</span><span>Formato livre</span><span>Sem exposição obrigatória</span></div></div><figure class="intro-qr"><img src="../assets/recursos/whatsapp-fofo-tech.jpg" alt="QR code do grupo FOFO TECH no WhatsApp"><figcaption>Grupo FOFO TECH no WhatsApp</figcaption></figure>`,`Convide à apresentação sem exigir imagem, voz ou informação pessoal. Contingência: apresentação oral breve ou registro em papel.`,`activity intro-slide`));

slides.push(slide(1,'Diagnóstico: como aprendemos no trabalho?',`<img src="../assets/recursos/mentimeter-como-aprendemos-no-trabalho.jpg" alt="Acesso ao Mentimeter para responder como aprendemos no trabalho">`,`Teste previamente QR e código. Informe se a participação é anônima. Peça respostas curtas sobre pessoas, fontes, experiências e tentativas mobilizadas para aprender no trabalho.`,`menti-entry`));

slides.push(slide(1,'O diagnóstico é uma escuta',`${tag('O que fizemos no Mentimeter?')}<h2>Antes de ensinar, procuramos compreender o ponto de partida.</h2>${prompt('Quando perguntamos “Como aprendemos no trabalho?”, o que estamos tentando descobrir?',`<p>Não buscamos uma resposta correta. Buscamos repertórios, experiências, ausências, padrões e diferenças que ajudem o formador a decidir como mediar o percurso.</p>`)}${example('Guarde esta distinção','Uma resposta diagnóstica é uma pista sobre o ponto de partida. Ela ainda não é prova de aprendizagem.')}`,`Leia algumas respostas sem expor pessoas. Agrupe padrões e ausências. Mostre como a leitura do diagnóstico altera exemplos, ritmo e perguntas do formador.`));

slides.push(slide(1,'Diagnóstico só ganha sentido quando muda uma decisão',`${tag('Da resposta à mediação')}<h2>Se o resultado não muda nada, por que perguntamos?</h2>${compare([['O grupo já domina o conceito','Reduza a explicação e proponha um caso mais exigente.','A decisão é aprofundar.'],['Há respostas muito divergentes','Peça justificativas e promova confronto de hipóteses.','A decisão é problematizar.'],['Poucas pessoas respondem','Investigue acesso, clareza, segurança e tempo.','A decisão é remover barreiras.'],['A pergunta foi mal compreendida','Reformule e teste outra evidência.','A decisão é revisar o instrumento.']])}`,`Use a tabela como exemplos de decisões. Pergunte aos participantes qual decisão tomariam diante de um resultado real.`));

slides.push(slide(2,'Problematização no Mentimeter',`<img src="../assets/recursos/mentimeter-problematizacao.jpg" alt="Acesso ao Mentimeter com a pergunta sobre o que a tecnologia modificou na experiência">`,`Oriente o acesso e mantenha as respostas ocultas até a maioria participar. Contingência: cartões com a mesma pergunta.`,`menti-entry`));

slides.push(slide(2,'A tecnologia modificou o quê?',`${tag('Agora observe a experiência')}<h2>O celular apenas substituiu o papel?</h2>${prompt('Ou a tecnologia mudou quem respondeu, quando respondeu, o que ficou visível e como o formador pôde agir?',`<p>Uma tecnologia educacional não é apenas um suporte. Ela reorganiza acesso, participação, representação, registro, feedback e memória da experiência.</p>`)}${example('Volte ao Mentimeter','O valor não estava na nuvem, no gráfico ou no QR. Estava na possibilidade de tornar o pensamento do grupo visível e utilizá-lo na mediação.')}`,`Revele as respostas. Não trate frequência como verdade. Pergunte o que foi ampliado, reduzido ou ocultado pela tecnologia.`));

slides.push(slide(2,'Mentimeter não é metodologia',`${tag('Uma correção necessária')}<h2>O Mentimeter faz a pergunta aparecer. Quem desenha a aprendizagem é o formador.</h2>${compare([['Ferramenta','Coleta e visualiza respostas.','É o ambiente técnico.'],['Estratégia pedagógica','Define por que perguntar, em que momento e para qual decisão.','É a intenção.'],['Mediação','Interpreta, problematiza, devolve e conecta as respostas ao conteúdo.','É a ação do formador.'],['Evidência','Mostra o que a resposta permite ou não concluir.','É o fundamento da decisão.']])}`,`Peça que os participantes nomeiem a metodologia ou estratégia usada no diagnóstico. Mostre que Mentimeter é recurso, não metodologia.`));

slides.push(slide(2,'Comece pela evidência',`${tag('Antes de escolher o tipo de questão')}<h2>O que você precisa tornar visível?</h2>${steps([['1 · Decisão','Que decisão pedagógica será informada?'],['2 · Ação','O que o participante fará para responder?'],['3 · Evidência','Que aspecto do pensamento ficará observável?'],['4 · Formato','Qual tipo de questão representa melhor essa evidência?'],['5 · Debriefing','Como as respostas voltarão à aprendizagem?']])}`,`Percorra o fluxo. Mostre que a escolha do formato vem depois da decisão, da ação e da evidência.`));

slides.push(slide(2,'Múltipla escolha',`${tag('Quando queremos comparar decisões')}<h2>Uma boa alternativa errada conta uma história.</h2>${example('Experimente','Durante um curso, 70% escolhem uma alternativa incorreta. O que o formador deve fazer primeiro? A) Repetir a explicação. B) Pedir justificativas e comparar critérios. C) Mostrar a resposta correta. D) Ignorar e avançar.')}${prompt('Por que a alternativa B produz melhor evidência?',`<p>Porque permite observar o raciocínio que sustentou a escolha. O percentual mostra onde olhar; a justificativa ajuda a compreender o que precisa ser revisto.</p>`)}`,`Aplique a questão e peça justificativas antes de revelar a análise. Distratores devem representar erros plausíveis, não pegadinhas.`));

slides.push(slide(2,'Nuvem de palavras',`${tag('Quando queremos mapear repertório inicial')}<h2>A palavra maior é a mais frequente. Não é necessariamente a mais importante.</h2>${example('Pergunta adequada','Em uma palavra, que condição mais favorece a aprendizagem no trabalho?')}${prompt('O que fazemos depois que a nuvem aparece?',`<p>Pedimos exemplos, agrupamos sentidos próximos, observamos ausências e confrontamos termos que parecem iguais. Sem debriefing, a nuvem é apenas uma imagem atraente.</p>`)}`,`Demonstre como termos semelhantes podem ter sentidos diferentes. Leia verbalmente resultados relevantes para acessibilidade.`));

slides.push(slide(2,'Resposta aberta',`${tag('Quando precisamos enxergar o raciocínio')}<h2>“Explique por quê” costuma revelar mais do que “Você concorda?”.</h2>${example('Pergunta de trabalho','Que decisão você tomaria neste caso e qual critério sustentaria sua escolha?')}${prompt('O que a resposta aberta exige do formador?',`<p>Tempo para leitura, segurança para participação, critérios de análise e cuidado antes de projetar conteúdo sensível ou identificável.</p>`)}`,`Oriente respostas curtas e contextualizadas. Use moderação quando disponível e nunca projete conteúdo sensível sem revisão.`));

slides.push(slide(2,'Escala, ranking e priorização',`${tag('Quando queremos comparar percepções ou critérios')}<h2>Números precisam de rótulos e contexto.</h2>${compare([['Escala','“Quanto você se sente capaz de executar esta tarefa?”','Mede percepção de confiança, não desempenho.'],['Ranking','“Ordene os critérios mais relevantes para esta decisão.”','Torna prioridades visíveis, mas pede justificativa.'],['100 pontos','“Distribua os pontos entre custo, risco, tempo e impacto.”','Explicita trade-offs e favorece comparação.']])}`,`Reforce que escala mede percepção. Para verificar capacidade, combine-a com caso, tarefa ou demonstração.`));

slides.push(slide(2,'O resultado não fala sozinho',`${tag('Leia com responsabilidade')}<h2>Participação, percepção e aprendizagem não são sinônimos.</h2>${compare([['Muitas respostas','Pode indicar adesão e acesso.','Ainda não informa qualidade do raciocínio.'],['Alta confiança','Pode indicar percepção positiva.','Ainda não demonstra capacidade de executar.'],['Mudança de voto','Pode indicar revisão de hipótese.','Pergunte o que mudou e por quê.'],['Concordância do grupo','Pode indicar consenso.','Investigue silêncio, pressão social e alternativas ausentes.']])}`,`Use um resultado real ou fictício. Peça que o grupo formule uma inferência legítima e uma conclusão que seria exagerada.`));

slides.push(slide(2,'Debriefing: a aprendizagem acontece depois do clique',`${tag('Não encerre na visualização')}<h2>O que apareceu? Por que apareceu? O que faremos com isso?</h2>${steps([['Descrever','Que padrões, diferenças e ausências vemos?'],['Interpretar','Que hipóteses explicam esse resultado?'],['Confrontar','Que conceitos, fontes ou exemplos desafiam as hipóteses?'],['Decidir','O que precisa ser mantido, revisto ou testado?'],['Transferir','Onde essa decisão aparece no trabalho?']])}`,`Conduza o debriefing sem corrigir imediatamente. Dê tempo para descrição antes de interpretação e decisão.`));

slides.push(slide(2,'Operação segura do Mentimeter',`${tag('Antes de abrir a votação')}<h2>Uma interação breve também precisa de acessibilidade, privacidade e contingência.</h2>${cards([['Teste','Confirme link, QR, código, rede, projeção e um voto de teste.'],['Explique','Informe finalidade, tempo, anonimato e visibilidade das respostas.'],['Inclua','Leia resultados relevantes e ofereça alternativa sem celular.'],['Proteja','Evite dados pessoais e revise respostas abertas antes de projetar.']])}${example('Plano B equivalente','Cartões, mãos levantadas ou conversa em pares devem preservar a mesma pergunta e a mesma decisão pedagógica.')}`,`Apresente o checklist. Códigos podem expirar ou mudar. Não exporte resultados sem finalidade e autorização.`));

slides.push(slide(3,'Da voz do grupo às fontes',`<div class="visual-dialogue"><div>${tag('Uma mudança de escala')}<h2>O Mentimeter nos ajudou a escutar o grupo.</h2><p>E quando precisamos escutar também documentos, vídeos, normas, artigos e materiais de curso?</p><strong>Entramos no Gemini Notebook.</strong></div><img src="../assets/imagens/fofo-tech-aprendizagem-em-rede.png" alt="Pessoas, livros e conexões digitais representando aprendizagem em rede"></div>`,`Faça a transição: da coleta de respostas do grupo para a investigação de um corpus documental. Não apresente a IA como substituta da leitura.`));

slides.push(slide(3,'O que é o Gemini Notebook?',`${tag('NotebookLM · visão panorâmica')}<h2>Uma IA que conversa com as fontes que você escolhe.</h2>${prompt('O que muda quando o formador delimita o corpus?',`<p>A resposta fica ancorada em um conjunto de fontes selecionado. Isso aumenta a rastreabilidade e reduz a dispersão, mas não garante que o corpus seja correto, atual, suficiente ou livre de vieses.</p>`)}${example('Em uma frase','O Gemini Notebook ajuda a interrogar, relacionar e transformar fontes. Ele não é uma fonte autônoma de verdade.')}`,`Apresente a definição e abra uma citação em demonstração. Reforce que “ancorado” não significa “infalível”.`));

slides.push(slide(3,'O que ele faz e o que não faz',`${tag('Uma relação de trabalho responsável')}<h2>Use a IA como parceira de investigação, não como autora invisível.</h2>${compare([['Pode ajudar a localizar','Trechos, conceitos, convergências e contradições.','Você confere contexto e pertinência.'],['Pode ajudar a explicar','Ideias complexas em diferentes níveis de detalhe.','Você avalia precisão e linguagem.'],['Pode ajudar a produzir','Sínteses, mapas, quizzes, áudios e outros artefatos.','Você revisa, corrige e assume autoria.'],['Não deve decidir por você','O que é verdadeiro, ético ou adequado ao contexto.','O julgamento continua humano.']])}`,`Peça um exemplo de tarefa que pode ser assistida e outro de decisão que não deve ser terceirizada.`));

slides.push(slide(3,'Nosso mapa de uso',`${tag('Três etapas que organizam o trabalho')}<h2>Fontes → Prompts → Artefatos</h2>${steps([['FONTES','Que materiais delimitam o que a IA poderá mobilizar?'],['PROMPTS','Que pergunta orienta a investigação e explicita critérios?'],['CITAÇÕES','Que trechos sustentam a resposta e como serão conferidos?'],['ARTEFATOS','Que produto ajudará alguém a aprender, decidir ou aplicar?'],['REVISÃO','O que precisa ser corrigido antes do uso?']])}${example('Regra do dia','A qualidade começa no corpus, ganha direção no prompt e só termina depois da revisão do artefato.')}`,`Apresente o ciclo completo. Embora o curso agrupe o uso em três etapas, citações e revisão atravessam todo o processo.`));

slides.push(slide(4,'Fontes: antes do prompt, vem o corpus',`${tag('Etapa 1 · Fontes')}<h2>Uma pergunta bem escrita não conserta um conjunto fraco de fontes.</h2>${prompt('Se o notebook recebeu materiais desatualizados, repetitivos ou pouco confiáveis, o que podemos esperar?',`<p>Respostas coerentes com um corpus inadequado. A IA pode organizar bem um problema mal alimentado.</p>`)}${example('Princípio de curadoria','Corpus antes do prompt: delimite problema, público, período, autoridade e diversidade antes de carregar arquivos.')}`,`Faça uma pausa para o participante identificar um corpus que usaria em uma formação real.`));

slides.push(slide(4,'O que pode entrar como fonte?',`${tag('Não confunda possibilidade técnica com autorização')}<h2>Documentos, páginas, vídeos e outros materiais podem formar o caderno.</h2>${cards([['Documentos','PDFs, textos, apresentações, relatórios e materiais de curso.'],['Web','Páginas públicas relevantes e estáveis.'],['Vídeos','Conteúdo disponível e compatível com o recurso da conta.'],['Notas próprias','Contexto, perguntas e registros sem dados indevidos.']])}${prompt('A pergunta decisiva não é apenas “a ferramenta aceita?”.',`<p>Pergunte também: tenho autorização para usar? O material é necessário? Está atualizado? Há dados pessoais, processuais, sigilosos ou protegidos?</p>`)}`,`Recursos aceitos podem variar por conta e atualização. Não carregue conteúdo sensível em demonstrações.`));

slides.push(slide(4,'Como pesquisar fontes',`${tag('Pesquisa com propósito')}<h2>Comece pelo problema que precisa ser compreendido, não pela vontade de acumular arquivos.</h2>${steps([['Delimite','Que problema, público, contexto e período estão em foco?'],['Busque','Quais fontes primárias, oficiais ou especializadas podem responder?'],['Compare','Há diversidade de perspectivas e versões atualizadas?'],['Selecione','Cada fonte acrescenta algo necessário ao corpus?'],['Registre','De onde veio, quando foi acessada e por que entrou?']])}`,`Use um exemplo real de formação. Mostre que quantidade de fontes não substitui pertinência e diversidade.`));

slides.push(slide(4,'Como curar fontes',`${tag('Faça uma auditoria antes do upload')}<h2>Uma fonte entra porque merece confiança e cumpre uma função.</h2>${compare([['Autoridade','Quem produziu e com que responsabilidade?','Prefira fontes primárias e institucionais quando o tema exigir.'],['Atualidade','A data e a versão ainda são válidas?','Tecnologias, normas e políticas mudam.'],['Pertinência','A fonte responde ao problema e ao público?','Texto bom também pode ser irrelevante.'],['Diversidade','O corpus inclui contrapontos e limites?','Evite apenas confirmar a hipótese inicial.'],['Autorização','O uso respeita direitos, sigilo e finalidade?','Possibilidade de upload não equivale a permissão.']])}`,`Peça que cada participante escolha o critério mais negligenciado em sua rotina e explique por quê.`));

slides.push(slide(4,'Corpus forte ou corpus frágil?',`${tag('Compare antes de prosseguir')}<h2>O mesmo prompt pode produzir resultados muito diferentes.</h2><div class="two-scenarios"><article><span>CORPUS FRÁGIL</span><p>Um post sem autoria, um PDF antigo e três textos que repetem a mesma opinião.</p><strong>Resultado provável:</strong><p>Síntese fluida, pouco diversa e difícil de sustentar.</p></article><article><span>CORPUS FORTE</span><p>Documento oficial atual, estudo especializado, caso real anonimizado e contraponto fundamentado.</p><strong>Resultado provável:</strong><p>Análise mais rastreável, comparável e útil para decidir.</p></article></div>${prompt('Qual fonte está faltando no seu corpus?',`<p>Às vezes, a ausência mais importante é justamente a fonte que poderia contrariar nossa hipótese.</p>`)}`,`Peça que o grupo melhore o corpus frágil. Não prometa que corpus forte elimina erros.`));

slides.push(slide(4,'Auditoria rápida das fontes',`${tag('Antes de conversar com a IA')}<h2>Consigo explicar por que cada fonte está aqui?</h2>${cards([['Identificação','Título, autoria, data, versão e origem estão claros?'],['Função','A fonte oferece conceito, regra, evidência, caso, contraponto ou exemplo?'],['Limite','Que lacuna, viés ou contexto precisa ser lembrado?'],['Proteção','Há dado pessoal, sensível, sigiloso ou uso não autorizado?']])}${example('Produto da etapa','Uma lista enxuta de fontes, cada uma com função e limite registrados.')}`,`Transforme o checklist em atividade. A equipe deve remover pelo menos uma fonte redundante ou inadequada.`));

slides.push(slide(4,'Fontes também exigem responsabilidade',`${tag('Privacidade, direitos e contexto')}<h2>Nem tudo que podemos copiar devemos carregar.</h2>${prompt('Antes do upload, responda quatro perguntas.',`<ol><li>O conteúdo é necessário para a finalidade?</li><li>Tenho autorização para utilizá-lo?</li><li>Posso anonimizar ou trabalhar com caso fictício?</li><li>Quem terá acesso ao notebook e por quanto tempo?</li></ol>`)}${example('Regra prática','Em exercícios, prefira fontes públicas, autorizadas, fictícias ou adequadamente anonimizadas.')}`,`Não solicite compartilhamento de documentos sensíveis. Oriente validação institucional quando houver dúvida.`));

slides.push(slide(5,'Prompts: a pergunta organiza a investigação',`${tag('Etapa 2 · Prompts')}<h2>Prompt não é palavra mágica. É um briefing para uma tarefa intelectual.</h2>${prompt('O que a IA precisa saber para responder de modo útil?',`<p>Qual é o objetivo, que papel deverá cumprir, quais fontes deve considerar, que operação realizará, qual produto entregará e quais critérios ou limites respeitará.</p>`)}${example('Lembrete','Um prompt sofisticado não corrige fontes frágeis. Ele apenas dá direção ao material disponível.')}`,`Convide o grupo a comparar prompt como comando e prompt como briefing.`));

slides.push(slide(5,'Anatomia de um prompt útil',`${tag('Dê contexto sem transformar o prompt em labirinto')}<h2>Objetivo + contexto + ação + critérios + formato + verificação</h2>${compare([['Objetivo','Para que a resposta será usada?','“Apoiar uma atividade sobre avaliação diagnóstica.”'],['Contexto','Quem é o público e qual é a situação?','“Formadores do Judiciário em oficina presencial.”'],['Ação','Que operação deve ser realizada?','“Compare, identifique divergências e proponha perguntas.”'],['Critérios','O que precisa orientar a resposta?','“Use somente as fontes e sinalize lacunas.”'],['Formato','Como a resposta deve ser organizada?','“Tabela com evidência e citação.”']])}`,`Mostre que nem todo prompt precisa conter todos os campos, mas a ausência deve ser deliberada.`));

slides.push(slide(5,'Prompt fraco e prompt melhorado',`${tag('Observe a diferença')}<h2>“Faça um resumo” entrega o controle da tarefa para a ferramenta.</h2><div class="two-scenarios"><article><span>PROMPT FRACO</span><p>Faça um resumo destes documentos.</p><strong>Problema:</strong><p>Não define público, finalidade, foco, critérios nem verificação.</p></article><article><span>PROMPT MELHORADO</span><p>Com base apenas nas fontes selecionadas, explique para formadores iniciantes três diferenças entre avaliação diagnóstica e avaliação formativa. Para cada diferença, apresente um exemplo de decisão pedagógica e indique a citação que sustenta a explicação. Sinalize divergências entre as fontes.</p></article></div>`,`Leia os dois prompts e peça ao grupo que nomeie as decisões explicitadas no segundo.`));

slides.push(slide(5,'Uma escada de perguntas',`${tag('Não pare na primeira síntese')}<h2>Comece localizando. Termine aplicando e criticando.</h2>${steps([['LOCALIZAR','Onde as fontes tratam do conceito?'],['EXPLICAR','Como o conceito é definido e exemplificado?'],['COMPARAR','Em que as fontes convergem ou divergem?'],['CRITICAR','Que limites, lacunas e pressupostos aparecem?'],['APLICAR','Como o conceito muda uma decisão real?'],['REVISAR','Que evidência ainda falta antes de usar?']])}`,`Demonstre a escada com um tema do curso. Mostre que perguntas sucessivas produzem investigação, não uma resposta final instantânea.`));

slides.push(slide(5,'Prompts para o trabalho do formador',`${tag('Modelos para adaptar, não copiar mecanicamente')}<h2>Que conversa você quer ter com as fontes?</h2>${cards([['Inventariar','Liste os conceitos centrais e associe cada um às fontes que o sustentam.'],['Comparar','Mostre convergências, divergências e lacunas entre as fontes.'],['Problematizar','Crie um caso que torne visível um erro de compreensão recorrente.'],['Transferir','Proponha uma aplicação ao trabalho e explicite condições e limites.']])}${example('Ação do participante','Escolha um modelo, adapte ao seu contexto e explique qual evidência a resposta deverá oferecer.')}`,`Evite tratar os modelos como receitas. O participante deve justificar a adaptação.`));

slides.push(slide(5,'Citações: volte ao trecho de origem',`${tag('Rastreabilidade não é garantia automática')}<h2>A citação permite conferir. A conferência continua sendo sua.</h2>${steps([['Abra','Acesse o trecho indicado pela resposta.'],['Leia','Considere o contexto antes e depois do trecho.'],['Compare','Verifique se a síntese preserva o sentido da fonte.'],['Cruze','Procure confirmação, divergência ou lacuna em outra fonte.'],['Registre','Indique o nível de confiança e o que ainda precisa ser validado.']])}${example('Pergunta crítica','A fonte sustenta exatamente esta afirmação ou apenas algo parecido?')}`,`Faça uma demonstração real de abertura de citação. Aponte uma inferência que extrapolaria o trecho.`));

slides.push(slide(5,'Quando a resposta parece boa demais',`${tag('Pare antes de copiar')}<h2>Fluidez não é sinônimo de precisão.</h2>${prompt('Que sinais pedem revisão?',`<ul><li>Certeza sem citação ou com citação indireta.</li><li>Generalização maior que o corpus.</li><li>Conceitos tratados como equivalentes sem base.</li><li>Ausência de contrapontos presentes nas fontes.</li><li>Recomendação que ignora contexto institucional.</li></ul>`)}${example('Ação responsável','Peça à IA que identifique lacunas, depois confira você mesmo. A ferramenta também pode omitir suas próprias limitações.')}`,`Use este slide como protocolo de desaceleração. Não aceite resposta apenas porque parece bem escrita.`));

slides.push(slide(6,'Artefatos: a resposta ganha forma',`${tag('Etapa 3 · Artefatos')}<h2>Um artefato não é o ponto final. É uma nova representação que precisa ser examinada.</h2>${prompt('Que produto ajudará o participante a fazer o quê?',`<p>Estudar, comparar, recuperar, explicar, discutir, decidir, produzir ou aplicar? O formato só faz sentido quando serve a uma ação de aprendizagem.</p>`)}${example('Regra','Não escolha “áudio”, “quiz” ou “infográfico” pela novidade. Escolha pela função pedagógica e pelas condições de acesso.')}`,`Faça os participantes dizerem uma ação antes de nomear um artefato.`));

slides.push(slide(6,'Relatórios e mapas',`${tag('Quando precisamos organizar relações')}<h2>O relatório explica. O mapa ajuda a enxergar conexões. Nenhum deles pensa pelo leitor.</h2>${compare([['Relatório ou guia','Organiza sínteses, comparações, perguntas frequentes e argumentos.','Peça evidências, limites e destinatário.'],['Mapa mental','Representa conceitos, hierarquias e relações.','Confira simplificações e ligações indevidas.'],['Linha do tempo','Ordena acontecimentos e mudanças.','Verifique datas, causalidade e lacunas.']])}${example('Uso FOFO','Entregue o mapa com uma pergunta: “Que relação está faltando e qual conexão você mudaria?”')}`,`Mostre como transformar consumo do artefato em ação do participante.`));

slides.push(slide(6,'Áudio e vídeo',`${tag('Quando a narrativa ajuda a revisar')}<h2>Ouvir e assistir podem ampliar acesso, mas não substituem fontes nem atividade.</h2>${prompt('Como evitar consumo passivo?',`<p>Antecipe uma pergunta, ofereça roteiro ou transcrição, proponha pausa para registro e peça comparação com a fonte original.</p>`)}${example('Configuração pedagógica','Gere uma visão geral curta para revisão e solicite que o participante identifique uma simplificação, uma evidência e uma dúvida.')}`,`Lembre que disponibilidade, idioma e formatos podem variar conforme conta e atualização. Ofereça alternativa textual.`));

slides.push(slide(6,'Quiz e flashcards',`${tag('Quando queremos recuperar e discriminar')}<h2>Recordar ajuda a aprender. Mas o objetivo pode exigir decidir, justificar e aplicar.</h2>${compare([['Flashcards','Apoiam recuperação de conceitos, termos e relações.','Inclua exemplo e contraste, não apenas definição.'],['Quiz','Permite testar compreensão e oferecer feedback.','Use distratores plausíveis e explique o raciocínio.'],['Caso curto','Exige selecionar critério e tomar decisão.','É necessário quando o objetivo ultrapassa memória.']])}`,`Pergunte qual formato observa melhor o objetivo real. Combine quiz com justificativa quando necessário.`));

slides.push(slide(6,'Infográfico e apresentação',`${tag('Quando precisamos comunicar uma síntese')}<h2>Design atraente pode ocultar erro conceitual.</h2>${prompt('Antes de usar, faça uma auditoria.',`<p>As relações estão corretas? As fontes aparecem? Há excesso de simplificação? O texto é legível? A informação depende apenas de cor? O produto respeita autoria e contexto?</p>`)}${example('Uso responsável','Trate o artefato gerado como primeiro rascunho. Edite linguagem, hierarquia, exemplos, acessibilidade e referências.')}`,`Não apresente slides gerados sem revisão. Mostre uma correção concreta feita pelo formador.`));

slides.push(slide(6,'Escolha o artefato pela ação',`${tag('Uma pergunta para cada escolha')}<h2>O que o participante fará com esse produto?</h2>${compare([['Se precisa compreender relações','Mapa ou quadro comparativo.','Peça correção, complemento ou explicação das conexões.'],['Se precisa recuperar conceitos','Flashcards ou quiz.','Inclua feedback e nova tentativa.'],['Se precisa discutir perspectivas','Áudio, vídeo ou relatório contrastivo.','Peça evidências e contrapontos.'],['Se precisa aplicar','Caso, roteiro, checklist ou plano de ação.','Exija decisão, justificativa e condição de uso.']])}`,`Convide o participante a substituir um artefato escolhido por novidade por outro mais coerente com a ação esperada.`));

slides.push(slide(6,'Como configurar um artefato',`${tag('Antes de clicar em gerar')}<h2>Dê ao produto um destinatário, uma função e critérios de qualidade.</h2>${steps([['PÚBLICO','Quem utilizará e que repertório possui?'],['FINALIDADE','Que ação ou decisão o artefato apoiará?'],['FOCO','Que fontes, conceitos e limites precisam aparecer?'],['FORMATO','Extensão, linguagem, estrutura e acessibilidade.'],['CRITÉRIOS','Precisão, rastreabilidade, pertinência e possibilidade de revisão.']])}`,`Faça os participantes configurar um mesmo artefato para dois públicos e observar como as escolhas mudam.`));

slides.push(slide(6,'Auditoria do artefato',`${tag('A autoria começa na revisão')}<h2>Antes de compartilhar, consigo responder por cada afirmação?</h2>${cards([['Fidelidade','O produto preserva o sentido das fontes?'],['Suficiência','Há lacunas ou generalizações que precisam ser sinalizadas?'],['Pedagogia','O artefato provoca uma ação de aprendizagem?'],['Acessibilidade','Existe alternativa e a linguagem é utilizável pelo público?'],['Autoria','O que foi reescrito, contextualizado e assumido por mim?'],['Proteção','Há dado, imagem ou conteúdo que não deveria circular?']])}`,`Use o checklist sobre um artefato real. Exija pelo menos uma correção antes de considerar o produto pronto.`));

slides.push(slide(7,'O ciclo completo',`${tag('Agora conecte as três etapas')}<h2>Fonte bem curada. Pergunta bem orientada. Artefato bem revisado.</h2>${steps([['PROBLEMA','Que situação profissional precisa ser compreendida?'],['FONTES','Que corpus confiável e autorizado sustenta a investigação?'],['PROMPTS','Que perguntas localizam, comparam, criticam e aplicam?'],['ARTEFATO','Que produto apoiará uma ação de aprendizagem?'],['REVISÃO','Que evidências, limites e correções precisam aparecer?'],['TRANSFERÊNCIA','Como isso será usado e verificado no trabalho?']])}`,`Retome o ciclo e peça um exemplo de decisão em cada etapa.`));

slides.push(slide(7,'Exemplo completo: do problema ao produto',`${tag('Acompanhe um caso FOFO')}<h2>Como apoiar gestores a oferecer feedback mais específico?</h2>${compare([['Fontes','Política institucional, guia de feedback, estudo sobre comportamento observável e dois casos anonimizados.','Corpus combina regra, conceito e prática.'],['Prompts','Compare critérios, identifique erros recorrentes e crie dois casos contrastantes com citações.','A investigação tem finalidade e verificação.'],['Artefato','Guia curto + quiz com justificativa + roteiro de conversa.','Cada produto apoia uma ação diferente.'],['Revisão','Conferir citações, linguagem, risco de exposição e aderência institucional.','A autoria final é dos formadores.']])}`,`Peça ao grupo que identifique o que mudaria se o público ou o contexto fosse outro.`));

slides.push(slide(7,'Sua vez: desenhe um pequeno ciclo',`${tag('Prática de retomada')}<h2>Escolha uma formação real e responda sem começar pela ferramenta.</h2>${prompt('1. Que problema profissional será enfrentado?<br>2. Que fontes formariam um corpus suficiente?<br>3. Que prompt ajudaria a comparar ou aplicar?<br>4. Que artefato apoiaria uma ação observável?<br>5. Como você verificaria e revisaria o resultado?')}${example('Produto esperado','Um ciclo Fontes → Prompts → Artefatos com finalidade, evidência, critérios e um limite explícito.')}`,`Dê tempo individual e depois promova revisão em dupla. Não aceite apenas nomes de ferramentas como resposta.`,`activity`));

slides.push(slide(7,'Um feedback que produz nova versão',`${tag('Revise em pares')}<h2>Não diga apenas “gostei”. Ajude o colega a decidir melhor.</h2>${cards([['Uma força','Que escolha está coerente com o problema?'],['Uma pergunta','Que pressuposto ou lacuna precisa ser explicitado?'],['Uma evidência','Que fonte ou critério sustentará a decisão?'],['Uma mudança','O que deve ser revisto antes do uso?']])}${example('Condição de conclusão','O ciclo só termina depois que o autor registra e aplica ao menos uma revisão.')}`,`Oriente feedback específico e respeitoso. Depois, devolva tempo para a nova versão.`));

slides.push(slide(8,'Síntese do Dia 1',`${tag('Retome a conversa')}<h2>Começamos escutando pessoas. Depois aprendemos a conversar com fontes.</h2>${compare([['Mentimeter','Tornou respostas do grupo visíveis para orientar a mediação.','Pergunta, leitura, debriefing e decisão.'],['Fontes','Delimitaram o conhecimento mobilizado pela IA.','Curadoria, autorização, diversidade e limites.'],['Prompts','Organizaram a investigação do corpus.','Objetivo, ação, critérios, formato e verificação.'],['Artefatos','Transformaram a síntese em produtos para aprender e agir.','Função pedagógica, auditoria, revisão e autoria.']])}`,`Faça a síntese pedindo que os participantes completem cada linha com um exemplo vivido.`));

slides.push(slide(8,'Cheque sua compreensão',`${tag('Converse consigo antes de fechar')}<h2>Você consegue explicar sem repetir o nome da ferramenta?</h2>${prompt('1. Por que uma resposta diagnóstica não é prova de aprendizagem?<br>2. O que o debriefing acrescenta ao Mentimeter?<br>3. Por que o corpus vem antes do prompt?<br>4. O que uma citação permite e o que ela não garante?<br>5. Como um artefato se transforma em experiência de aprendizagem?')}${example('Se alguma resposta ainda estiver vaga','Volte ao bloco correspondente e procure o exemplo que ajuda a decidir, não apenas a definição.')}`,`Use as perguntas como recuperação ativa. Evite responder imediatamente; peça exemplos do grupo.`));

slides.push(slide(8,'Ticket de saída',`${tag('Do curso para o trabalho')}<h2>Que decisão você fará de modo diferente?</h2>${cards([['Antes','Eu costumava escolher a tecnologia por...'],['Agora','Passei a considerar indispensável...'],['Aplicação','Uma formação que vou revisar é...'],['Evidência','Saberei que a mudança funcionou quando...']])}${prompt('Registre também um limite.',`<p>Em que situação você decidiria não usar Mentimeter ou Gemini Notebook?</p>`)}`,`Recolha respostas para regular o encontro seguinte. Procure mudança de critério, não preferência por ferramenta.`,`activity`));

slides.push(`<section class="cover" data-topic="8" data-title="Fechamento" data-note="Feche retomando o princípio: tecnologia ganha valor quando amplia uma ação de aprendizagem, produz evidência útil e permanece sob julgamento responsável."><div class="cover-grid"><div>${tag('FOFO TECH · Dia 1')}<h1>A ferramenta amplia.<span>O formador dá sentido.</span></h1><p class="lead">Escute pessoas, cure fontes, formule perguntas, revise artefatos e devolva tudo à prática.</p></div><div class="logo-stage"><img src="../assets/logo-cjud.jpg" alt="Logo do CJUD"></div></div></section>`);

const html = `<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FOFO TECH · Dia 1 · Mentimeter e Gemini Notebook</title>
<meta name="description" content="Material instrucional e dialogado do Dia 1 do FOFO TECH: Mentimeter, fontes, prompts e artefatos no Gemini Notebook.">
<link rel="icon" href="../assets/logo-cjud.jpg">
<link rel="stylesheet" href="../vendor/reveal/reveal.css">
<link rel="stylesheet" href="../assets/slides.css">
</head>
<body>
<a class="slide-skip" href="#fofo-slides">Ir para os slides</a>
<a class="portal-return" href="../dia-1/" aria-label="Voltar à página do Dia 1">← Dia 1</a>
<div class="reveal" id="fofo-slides"><div class="slides">
${slides.join('\n\n')}
</div></div>
<div class="facilitator-tools" aria-label="Ferramentas de apresentação">
  <button type="button" id="prevSlide" class="nav-button" aria-label="Slide anterior" title="Slide anterior · Page Up ou seta para a esquerda">‹</button>
  <button type="button" id="nextSlide" class="nav-button" aria-label="Próximo slide" title="Próximo slide · Page Down, espaço ou seta para a direita">›</button>
  <span class="tool-separator" aria-hidden="true"></span>
  <button type="button" id="fullscreenToggle" aria-label="Entrar em tela cheia" aria-pressed="false" title="Tela cheia · tecla F">⛶</button>
  <button type="button" id="timerToggle" aria-label="Iniciar ou pausar temporizador" title="Iniciar ou pausar temporizador · tecla T">▶</button>
  <button type="button" id="timerDisplay" aria-label="Configurar temporizador" title="Configurar temporizador">05:00</button>
  <button type="button" id="timerReset" aria-label="Reiniciar temporizador" title="Reiniciar temporizador · tecla R">↺</button>
  <button type="button" id="notesOpen" aria-label="Abrir notas do apresentador" title="Notas do apresentador · tecla N">N</button>
  <span id="slideStatus" class="sr-only" aria-live="polite"></span>
</div>
<dialog class="timer-dialog" id="timerDialog"><form method="dialog"><button class="dialog-close" value="cancel" aria-label="Fechar">×</button><h2>Temporizador</h2><label>Minutos <input id="timerMinutes" type="number" min="0" max="180" value="5"></label><label>Segundos <input id="timerSeconds" type="number" min="0" max="59" value="0"></label><div class="timer-presets"><button type="button" data-min="1">1 min</button><button type="button" data-min="3">3 min</button><button type="button" data-min="5">5 min</button><button type="button" data-min="10">10 min</button><button type="button" data-min="15">15 min</button></div><button class="timer-apply" value="default">Aplicar</button></form></dialog>
<script src="../vendor/reveal/reveal.js"></script>
<script src="../vendor/reveal/plugin/notes/notes.js"></script>
<script src="../assets/slides.js"></script>
</body>
</html>`;

await fs.writeFile(destination, html);

const topicNames = ['Abertura','Diagnóstico','Mentimeter','Transição','Fontes','Prompts','Artefatos','Integração','Síntese'];
const blueprint = {
  Global_Settings: {
    Aspect_Ratio: '16:9',
    Purpose: 'material instrucional, dialogado e de retomada',
    Design_Style: ['institucional','tech','dialogado','legível em projeção','estudável sem a fala do formador'],
    Interaction: ['menu por tópico','setas e teclado','gesto horizontal','tela cheia','notas do apresentador','temporizador','hash por slide'],
    Accessibility: ['foco visível','rótulos ARIA','movimento reduzido','alto contraste','alternativas e contingências']
  },
  Slides: slides.map((markup, index) => {
    const title = markup.match(/data-title="([^"]+)"/)?.[1] ?? `Slide ${index + 1}`;
    const topic = Number(markup.match(/data-topic="(\d+)"/)?.[1] ?? 0);
    const classes = markup.match(/<section class="([^"]*)"/)?.[1] ?? '';
    let type = 'Dialogue';
    if (classes.includes('cover')) type = index === slides.length - 1 ? 'BackCover' : 'Cover';
    else if (classes.includes('menti-entry')) type = 'FullImage';
    else if (classes.includes('activity')) type = 'Activity';
    return { Page: String(index + 1).padStart(2, '0'), Type: type, Topic: topicNames[topic], Title: title };
  })
};
await fs.writeFile(new URL('../blueprint-dia-1.json', import.meta.url), `${JSON.stringify(blueprint, null, 2)}\n`);

const matrix = `# Matriz metodológica · FOFO TECH · Dia 1\n\n## Finalidade\n\nMaterial instrucional e dialogado para estudo, retomada e transferência. O percurso recupera a experiência real do Dia 1: diagnóstico e problematização com Mentimeter; visão panorâmica do Gemini Notebook; aprofundamento no ciclo Fontes, Prompts e Artefatos.\n\n## Cadeia de aprendizagem\n\nRealidade e repertório → pergunta diagnóstica → leitura da evidência → problematização → fundamentação → prática guiada → verificação → revisão → transferência.\n\n## Blocos\n\n| Bloco | Slides | Ação do participante | Evidência | Mediação |\n|---|---:|---|---|---|\n| Abertura | 1–5 | Estabelecer contrato de leitura e aprendizagem | Expectativas e formas de participação | Acolher e situar o material como conversa |\n| Diagnóstico | 6–9 | Explicitar como aprende no trabalho e interpretar o ponto de partida | Repertórios, padrões, ausências e diferenças | Transformar respostas em decisão pedagógica |\n| Mentimeter | 10–20 | Responder, justificar, comparar e analisar tipos de questão | Escolhas, justificativas, prioridades e percepções | Conduzir debriefing e distinguir participação de aprendizagem |\n| Transição | 21–24 | Relacionar escuta do grupo e investigação de fontes | Definição e limites do Gemini Notebook | Delimitar IA ancorada em fontes e julgamento humano |\n| Fontes | 25–31 | Pesquisar, selecionar, curar e auditar o corpus | Corpus com função, limite e autorização registrados | Questionar autoridade, atualidade, diversidade e proteção |\n| Prompts | 32–38 | Formular, melhorar e verificar perguntas ao corpus | Prompts contextualizados e citações conferidas | Modelar investigação progressiva e desacelerar a aceitação |\n| Artefatos | 39–46 | Selecionar, configurar e auditar produtos | Artefato revisado para uma ação de aprendizagem | Relacionar formato, função, acessibilidade e autoria |\n| Integração | 47–50 | Desenhar e revisar um ciclo completo | Fontes → Prompts → Artefatos com critérios e limite | Oferecer feedback e exigir nova versão |\n| Síntese | 51–54 | Recuperar, explicar e transferir | Mudança de critério e aplicação declarada | Sistematizar e preparar continuidade |\n\n## Critérios de qualidade\n\n1. A pergunta antecede a ferramenta.\n2. A evidência informa uma decisão real.\n3. O diagnóstico não é tratado como prova de aprendizagem.\n4. O corpus é curado antes do prompt.\n5. Citações são abertas e conferidas.\n6. Artefatos são tratados como rascunhos auditáveis.\n7. Acessibilidade, privacidade, autoria e contingência integram o desenho.\n8. Toda prática termina com revisão e possibilidade de transferência.\n`;
await fs.writeFile(new URL('../reports/MATRIZ-METODOLOGICA-DIA-1.md', import.meta.url), matrix);

console.log(`Dia 1 dialogado gerado com ${slides.length} slides, blueprint e matriz atualizados.`);
